### ISSUE TITLE
Z-Layouts

### ISSUE THREAD

**Issue by stylesuxx** [mathiasvr/bluejay-configurator#14]
Z-Layout are missing from the [esc.json](https://raw.githubusercontent.com/mathiasvr/bluejay-configurator/bluejay/js/bluejay_escs.json) which have been added to [v0.11 of the firmware](https://github.com/mathiasvr/bluejay/releases/tag/v0.11-test) - or is this just missing because of pre-release?

**Comment by mathiasvr** [comment]
Nice catch, I forgot that the blheli_s and bluejay esc definitions were in separate files.
