### ISSUE TITLE
Configurator doesn't exit on MacOs

### ISSUE THREAD

**Issue by AndreaB321** [mathiasvr/bluejay-configurator#17]
Hi there,
When I click on the bluejay-configurator quit button, the app doesn't close itself.
I have to force quit to terminate it.

**Comment by mathiasvr** [comment]
Yes this is quite unfortunate.

Currently the easiest way to quit is clicking the red x to close the window.

**Comment by mathiasvr** [comment]
This should be fixed by https://github.com/mathiasvr/bluejay-configurator/commit/33c3dba2afda2933ca2e336afc7095d9ab9964f2.
Will be released as `v1.3.6`.
