### ISSUE TITLE
Serial port not appears

### ISSUE THREAD

**Issue by aQuaplug** [mathiasvr/bluejay-configurator#20]
Serial port not appears Bluejay Configurator and esc-configurator.com.
It appears BLHeli Configurator and all other tools like Betaflight, Emuflight, iNav..ect connection correctly.
What should I check?
I'm using Windows 10 and Chrome.

**Comment by mathiasvr** [comment]
That's very strange, I don't know why that would happen. Have you tried restarting the computer?

**Comment by aQuaplug** [comment]
Unfortunately yes. I've tried it my desktop, laptop and office PC.
And just now I've reinstall drivers. But none of them success :(
Strange, still other tools connect correctly, and seems none has trouble like mine.
I'll reinstall Windows on clean and try again.

**Comment by aQuaplug** [comment]
I think it's caused by Chrome version.
It was after Chrome 83, my chrome apps couldn't access serial port.
I thought it was normal, just changed policy of chrome cause that and so other Chrome apps like Betaflight, BLHeli configurator starts released standalone version that times.
Other tools still using versions of Chrome below 83, and bluejay using 91.
I think I should solve this first, but I can't find any clue of this problem, but I found only few has same problem with me.

If anyone has clue of this, please lead me. :'(

**Comment by stylesuxx** [comment]
Hey @aQuaplug Chrome Apps have been faded out for quite some time, see here => https://blog.chromium.org/2020/08/changes-to-chrome-app-support-timeline.html June this year was cutoff for all of them (unless you manually adjust a policy). You should use the stand alone versions of the configurators instead.

https://esc-configurator.com should be working with recent versions of Chromium based browsers, which version of Chrome are you currently running? Windows Edge browser is also Chromium based, so you could check with that too.

**Comment by aQuaplug** [comment]
> Hey @aQuaplug Chrome Apps have been faded out for quite some time, see here => https://blog.chromium.org/2020/08/changes-to-chrome-app-support-timeline.html June this year was cutoff for all of them (unless you manually adjust a policy). You should use the stand alone versions of the configurators instead.
> 
> https://esc-configurator.com should be working with recent versions of Chromium based browsers, which version of Chrome are you currently running? Windows Edge browser is also Chromium based, so you could check with that too.

Thanks for reply.
But iNav configurator ChromeApp version was released till 2.6.1(maybe Feb this year).
And it was unable to connect to me, but standalone version was fine.

Question, Then Chrome version text on all configurators(include standalone versions) startup log text is meaningless?
As I wrote above, only Bluejay configurator indicate Chrome version is larger than 83.
83 was that time start to faded out ChromeApp configurators and I was unable to connect ChromeApp just after that.
(I thought it was intended, but recent I knew iNav configurator still released this year)
And surely I'm using is latest 91 version of chrome now.
Not only one PC, my other computer's also can't access.
I was trying access with esc-configurator.com at cellphone too, port appears but never success connected to device.
But Speedybee app is fine.
It's so confusing. :(

Anyway, thanks very much.

**Comment by stylesuxx** [comment]
> But iNav configurator ChromeApp version was released till 2.6.1(maybe Feb this year).

I am a bit confued - inav configurator uses a stand alone version now for well over a year also 2.6.1 is available as stand alone version.

> And it was unable to connect to me, but standalone version was fine.

This is regarding inav configurator - latest stand alone version - v3.0.0? The stand alone version is working and you can connect to the flight controller?

> Question, Then Chrome version text on all configurators(include standalone versions) startup log text is meaningless?

The standalone versions come bundled with a Chrome browser, this is different from your web browser, the stand alone versions can have independent Chrome versions.

> As I wrote above, only Bluejay configurator indicate Chrome version is larger than 83.

Can you please try an older version of Bluejay configurator? Maybe try v1.3.1 just to see if you can connect to the flight-controller

> 83 was that time start to faded out ChromeApp configurators and I was unable to connect ChromeApp just after that.
> (I thought it was intended, but recent I knew iNav configurator still released this year)

I am really confused by this - how are you still obtaining Chrome Apps?

> And surely I'm using is latest 91 version of chrome now.

Can you please post a screenshot of https://esc-configurator.com with a flight controller attached and in the serial  selection menu?

> Not only one PC, my other computer's also can't access.

That really sound strange - which operating systems/ windows version do you have on the other computers? I assume you have tried temporarily disabling firewall and anti-virus, just to make sure they are not interfering?

> I was trying access with esc-configurator.com at cellphone too, port appears but never success connected to device.
> But Speedybee app is fine.

This is different, speedybee app is a native app, https://esc-configurator.com is not. There is a bug that on some Androids it does not work, Google is working on a possible solution, but right now it's hit or miss if https://esc-configurator.com will work on android phones.

**Comment by aQuaplug** [comment]
@stylesuxx 
Wow, so thankyou your care.
1. https://chrome.google.com/webstore/detail/inav-configurator/fmaidjmgkdkpafmbnmigkpdnpdhopgel?hl=en
   As I know, some chrome apps will not showing (after chages policy of chrome) as search in Chrome web store, but it's still 
   there, can access by google search.
2. Yes, standalone is working good.
   I'm using BLHeli, iNav, BF, EF, CF. Some of them even today.
3. Thanks, It was just my little curiousity.
4. I've tried already :'(
5. As no.1 answer.
6. 
   Only esc-configurator instance
![image](https://user-images.githubusercontent.com/76939444/123274911-def1a880-d53e-11eb-844c-1535d42431df.png)
   Wait enough, then open BLHeli configurator
![image](https://user-images.githubusercontent.com/76939444/123275058-fd57a400-d53e-11eb-94b8-5bd78b3f3797.png)
7. Windows 10 Pro 64bit all three computers, as screenshot above, korean language.
    I'm just using Windows Defender, thanks I'll try that.
8. Ah... got it. I'll try again on android when version update.

Really thankyou.
If with no success, sometime I'll clean install windows and STM drivers, and try bluejay, esc-configurator.com first.

**Comment by stylesuxx** [comment]
@aQuaplug I am sorry, I am really completely out of ideas. If it was just one computer with this issue, I'd say: Re-install windows, but when all have issues, it makes no sense to me whatsoever. I just tried on a Win 10 machine and had no issues at all. It's so mysterious.

This might be a long shot, but can you switch windows language to english? I can't imagine that this makes a difference, but I a desperate now :-)

You also tried this zdiag driver fixer thing, right? What makes no sense to me is, that it is working with some of the configurators. Bluejay configurator was forked direclty from BlHeli configurator, so older versions of Bluejay configurator should behave *exactly* as BlHeli configurator.

What happens when you try https://esc-configurator.com in Microsoft Edge browser?

Pinging @Noctaro - IIRC you were debugging a similar issue lately, in that case it was Win7 that was the issue, no?

**Comment by Noctaro** [comment]
@stylesuxx 
Yes, we had the problem on an very outdated version of Windows 7. No matter what we did, changing USB cables, USB ports and drivers, nothing could fix the problem. Betaflight configurator worked just fine, but we did not get a port in Chrome. After switching to another pc running an up to date Windows 10 it worked without any problems.

@aQuaplug What version of Windows 10 are you running? Is it up to date?

**Comment by aQuaplug** [comment]
@stylesuxx 
Nothing to sorry! :) Thanks again.
Yes, same with Edge. Failed with Zadig.
DFU appear with ImpulseRC driver fixer, but still no serial connection after disconnect.

@Noctaro
Yes, latest version. 21H1 now.
Congraturation. I envy you :)

**Comment by Noctaro** [comment]
@aQuaplug 
hmm, thats truly strange. I hoped it might be something that windows changed over time and updating could fix it. For now i also have no idea what may cause this problem. :/

**Comment by aQuaplug** [comment]
Solved.
Works correctly after clean install ENGLISH WINDOWS 10. Just change language isn't works.
I've heard some ImmersionRC's application has same problem with another language windows.
Still wonder why other similar tools worked fine but not this tool.
I hope these kind of problems will not happen on Windows11 :(
