### ISSUE TITLE
Unable to use non-standalone web app on Ubuntu 20

### ISSUE THREAD

**Issue by Stampede10343** [mathiasvr/bluejay-configurator#22]
I have tried Chrome, Chromium and Opera browsers and I get the 'Choose Serial Port', which opens up a dialog with no options available.

I am on Ubuntu 20.04. The standalone app works fine luckily, but I would like to be able to use the latest version of the app via the web app.

**Comment by mathiasvr** [comment]
Hi, you mean the ESC Configurator web app? Please report this issue here https://github.com/stylesuxx/esc-configurator.

I think someone else had this problem, it would be great to solve it.

**Comment by Stampede10343** [comment]
Oh my bad, I'll report it there!
